### ISSUE TITLE
Glosses

### ISSUE THREAD

**Issue by jcuenod** [eliranwong/LXX-Rahlfs-1935#1]
Hi Eliran,

I've been playing around with the LXX recently and I was looking for better glosses when I came across this repo. By the looks of things you've found a bunch of glosses here:https://github.com/eliranwong/LXX-Rahlfs-1935/blob/master/script/addEngGloss_v4.sh

I'm wondering how you got them (and part of my reason for asking this is that I'm trying to assess how reliable they are because I'm thinking of using them).

**Comment by eliranwong** [comment]
Hi James,

re sources of gloss, please read https://github.com/eliranwong/LXX-Rahlfs-1935/tree/master/06_English_gloss

**Comment by jcuenod** [comment]
So apart from the openscriptures data, are you saying that you went by hand through BDAG and LEH for glosses?

**Comment by eliranwong** [comment]
as I recall (I done that long time ago),
lexemes from open scriptures data were used to matched against the lexical entries in LJS and MLJS.
BDAG and LEH are only consulted, by hand, where there is no match in LJS or MLJS.

**Comment by jcuenod** [comment]
Okay, thanks.
